CREATE TABLE [User] (
    [UserId] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [Username] NVARCHAR(255) NOT NULL,
    [PasswordSalt] VARBINARY(MAX) NOT NULL,
    [PasswordHash] VARBINARY(MAX) NOT NULL,
    [IsAdmin] BIT NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE [List] (
    [ListId] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [UserId] UNIQUEIDENTIFIER NOT NULL,
    [ListName] NVARCHAR(255) NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY ([UserId]) REFERENCES [User]([UserId])
);

CREATE TABLE [ListBody] (
    [ListBodyId] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [ListId] UNIQUEIDENTIFIER NOT NULL,
    [UserId] UNIQUEIDENTIFIER NOT NULL,
    [ListBodyText] NVARCHAR(MAX) NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY ([ListId]) REFERENCES [List]([ListId]),
    FOREIGN KEY ([UserId]) REFERENCES [User]([UserId])
);

CREATE TABLE [Comment] (
    [CommentId] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [ListId] UNIQUEIDENTIFIER NOT NULL,
    [UserId] UNIQUEIDENTIFIER NOT NULL,
    [ListBodyId] UNIQUEIDENTIFIER NOT NULL,
    [CommentText] NVARCHAR(MAX) NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY ([ListId]) REFERENCES List,
    FOREIGN KEY ([UserId]) REFERENCES [User]([UserId]),
    FOREIGN KEY ([ListBodyId]) REFERENCES ListBody
);

CREATE TABLE [Reply] (
    [ReplyId] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [ListId] UNIQUEIDENTIFIER NOT NULL,
    [UserId] UNIQUEIDENTIFIER NOT NULL,
    [CommentId] UNIQUEIDENTIFIER NOT NULL,
    [ReplyText] NVARCHAR(MAX) NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY ([ListId]) REFERENCES [List]([ListId]),
    FOREIGN KEY ([UserId]) REFERENCES [User]([UserId]),
    FOREIGN KEY ([CommentId]) REFERENCES [Comment]([CommentId])
);

CREATE TABLE [ReplyLike] (
    [ReplyLikeId] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [ReplyId] UNIQUEIDENTIFIER NOT NULL,
    [UserId] UNIQUEIDENTIFIER NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY ([ReplyId]) REFERENCES [Reply]([ReplyId]),
    FOREIGN KEY ([UserId]) REFERENCES [User]([UserId])
);

CREATE TABLE [ReplyDislike] (
    [ReplyDislikeId] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [ReplyId] UNIQUEIDENTIFIER NOT NULL,
    [UserId] UNIQUEIDENTIFIER NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY ([ReplyId]) REFERENCES [Reply]([ReplyId]),
    FOREIGN KEY ([UserId]) REFERENCES [User]([UserId])
);

CREATE TABLE [CommentLike] (
    [CommentLikeId] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [CommentId] UNIQUEIDENTIFIER NOT NULL,
    [UserId] UNIQUEIDENTIFIER NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY ([CommentId]) REFERENCES [Comment]([CommentId]),
    FOREIGN KEY ([UserId]) REFERENCES [User]([UserId])
);

CREATE TABLE [CommentDislike] (
    [CommentDislikeId] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [CommentId] UNIQUEIDENTIFIER NOT NULL,
    [UserId] UNIQUEIDENTIFIER NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY ([CommentId]) REFERENCES [Comment]([CommentId]),
    FOREIGN KEY ([UserId]) REFERENCES [User]([UserId])
);