/* tslint:disable */
/* eslint-disable */
/**
 * PackAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Comment
 */
export interface Comment {
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    commentId?: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    listId?: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    listBodyId?: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    commentText?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Comment
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the Comment interface.
 */
export function instanceOfComment(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CommentFromJSON(json: any): Comment {
    return CommentFromJSONTyped(json, false);
}

export function CommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Comment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'commentId': !exists(json, 'commentId') ? undefined : json['commentId'],
        'listId': !exists(json, 'listId') ? undefined : json['listId'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'listBodyId': !exists(json, 'listBodyId') ? undefined : json['listBodyId'],
        'commentText': !exists(json, 'commentText') ? undefined : json['commentText'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
    };
}

export function CommentToJSON(value?: Comment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'commentId': value.commentId,
        'listId': value.listId,
        'userId': value.userId,
        'listBodyId': value.listBodyId,
        'commentText': value.commentText,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
    };
}

