/* tslint:disable */
/* eslint-disable */
/**
 * PackAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentLike
 */
export interface CommentLike {
    /**
     * 
     * @type {string}
     * @memberof CommentLike
     */
    commentLikeId?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentLike
     */
    commentId?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentLike
     */
    userId?: string;
    /**
     * 
     * @type {Date}
     * @memberof CommentLike
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the CommentLike interface.
 */
export function instanceOfCommentLike(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CommentLikeFromJSON(json: any): CommentLike {
    return CommentLikeFromJSONTyped(json, false);
}

export function CommentLikeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentLike {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'commentLikeId': !exists(json, 'commentLikeId') ? undefined : json['commentLikeId'],
        'commentId': !exists(json, 'commentId') ? undefined : json['commentId'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
    };
}

export function CommentLikeToJSON(value?: CommentLike | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'commentLikeId': value.commentLikeId,
        'commentId': value.commentId,
        'userId': value.userId,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
    };
}

