/* tslint:disable */
/* eslint-disable */
/**
 * PackAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateListRequest
 */
export interface CreateListRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateListRequest
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateListRequest
     */
    listName?: string | null;
}

/**
 * Check if a given object implements the CreateListRequest interface.
 */
export function instanceOfCreateListRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateListRequestFromJSON(json: any): CreateListRequest {
    return CreateListRequestFromJSONTyped(json, false);
}

export function CreateListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateListRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'listName': !exists(json, 'listName') ? undefined : json['listName'],
    };
}

export function CreateListRequestToJSON(value?: CreateListRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'listName': value.listName,
    };
}

