/* tslint:disable */
/* eslint-disable */
/**
 * PackAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCommentRequest
 */
export interface CreateCommentRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCommentRequest
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCommentRequest
     */
    listId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCommentRequest
     */
    listBodyId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCommentRequest
     */
    commentText?: string | null;
}

/**
 * Check if a given object implements the CreateCommentRequest interface.
 */
export function instanceOfCreateCommentRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateCommentRequestFromJSON(json: any): CreateCommentRequest {
    return CreateCommentRequestFromJSONTyped(json, false);
}

export function CreateCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCommentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'listId': !exists(json, 'listId') ? undefined : json['listId'],
        'listBodyId': !exists(json, 'listBodyId') ? undefined : json['listBodyId'],
        'commentText': !exists(json, 'commentText') ? undefined : json['commentText'],
    };
}

export function CreateCommentRequestToJSON(value?: CreateCommentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'listId': value.listId,
        'listBodyId': value.listBodyId,
        'commentText': value.commentText,
    };
}

