/* tslint:disable */
/* eslint-disable */
/**
 * PackAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateListBodyRequest
 */
export interface CreateListBodyRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateListBodyRequest
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateListBodyRequest
     */
    listId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateListBodyRequest
     */
    listBodyText?: string | null;
}

/**
 * Check if a given object implements the CreateListBodyRequest interface.
 */
export function instanceOfCreateListBodyRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateListBodyRequestFromJSON(json: any): CreateListBodyRequest {
    return CreateListBodyRequestFromJSONTyped(json, false);
}

export function CreateListBodyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateListBodyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'listId': !exists(json, 'listId') ? undefined : json['listId'],
        'listBodyText': !exists(json, 'listBodyText') ? undefined : json['listBodyText'],
    };
}

export function CreateListBodyRequestToJSON(value?: CreateListBodyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'listId': value.listId,
        'listBodyText': value.listBodyText,
    };
}

